### ISSUE TITLE
Incorrect page mappings among all the pages except 000#1a - #78b 

### ISSUE THREAD

**Issue by JLHwung** [kanripo/KR2k0044#1]
For example:

http://www.kanripo.org/text/KR2k0044/001#1a

Click `[001-1a]`

Expected: contents start with `浙江通志卷一`

Actual: contents start with `浙江通志卷首二`

**Comment by JLHwung** [comment]
The mapping is certainly better after #2 is merged. Yet the Juan 2 maps to juan 1 folio 31: http://www.kanripo.org/text/KR2k0044/004#1a

I don't think Juan 1 is spilt into two volume in WYG. So text should not be split like #2. I guess this time we should revise the data?

**Comment by cwittern** [comment]
Yes, this is incorrect now.  I usually try to put everything before 卷一 into the file _000.txt, so that means in this case what is now in 001 and 002 would also have to go into 000, with the page links adjusted, and then all the numbering changed to reflect the new sequence (eg. 003->001 etc).

**Comment by cwittern** [comment]
In this case, there is a difference between 首卷一, which is still part of the frontmatter and 卷一, which really starts the text.
