### ISSUE TITLE
Incomplete imglist for 卷一

### ISSUE THREAD

**Issue by JLHwung** [kanripo/KR2k0044#3]
https://raw.githubusercontent.com/kanripo/KR2k0044/_data/imglist/KR2k0044_003.txt

should return the digital fascimiles from `WYG0519/WYG0519-0085a.png` to `WYG0519/WYG0519-0124d.png` (the end of imglist/KR2k0044_004.txt).

Currently it returns only `WYG0519/WYG0519-0085a.png` to `WYG0519/WYG0519-0100b.png`.

The imglist of _005.txt is not correct, too. It should maps to the ranges of 卷2. I didn't check the other juans, but they are likely incorrect.

I don't know how to modify the `imglist`. @cwittern Is that open sourced?

**Comment by cwittern** [comment]
Yes, the list for the image links are in the branch `_data` , folder `imglist`. Every line describes one page link.
