### ISSUE TITLE
The contents in the response of http://www.kanripo.org/text/KR2k0044/000 needs update

### ISSUE THREAD

**Issue by JLHwung** [kanripo/KR2k0044#6]
![image](https://user-images.githubusercontent.com/3607926/126330327-08cb68a4-0f95-4d90-b679-1658ee0a4c7f.png)

卷二 is missing, and they map to wrong juans. They should sync with the `README.org`. It seems that the contents are rendered in HTML and I don't know how to modify it.

**Comment by cwittern** [comment]
This should be OK now.  The reason is that for performance improvement, the TOC is cached (it is generated on the fly from the files, but only if necessary). Now the cache has expired and a new TOC has been generated.
